#!/bin/zsh

assert() {
  expected="$1"
  input=$2

  ./zig-out/bin/kitwacc $input
  gcc -static -o test/kitwacc test/output.s
  ./test/kitwacc
  actual="$?"

  if [ $actual = $expected ]; then
    echo "TEST:PASSED $input => $actual"
  else
    echo "TEST:FAILED $input => $expected expected, but got $actual"
    exit 1
  fi
}

assert 7 7
assert 7 3+4
assert 21 5+20-4

echo OK
