#!/bin/zsh

assert() {
  expected="$1"
  input=$2

  ./zig-out/bin/kitwacc $input
  gcc -static -o test/kitwacc test/output.s
  ./test/kitwacc
  actual="$?"

  if [ $actual = $expected ]; then
    echo "TEST:PASSED $input => $actual"
  else
    echo "TEST:FAILED $input => $expected expected, but got $actual"
    exit 1
  fi
}

assert 7  7
assert 7  3+4
assert 6  3+4-1
assert 21 5+20-4
assert 41 '12 + 34 - 5 '
assert 2  '3 - 2 + 5 + 7  -11'
assert 47 '5 + 6 * 7'
assert 15 '5 * (9-6)'
assert 4  '(3+5) / 2'
assert 10 '-10+20'
assert 10 '- -10'
assert 10 '- - +10'

assert 0 '0==1'
assert 1 '42==42'
assert 1 '0!=1'
assert 0 '42!=42'

assert 1 '0<1'
assert 0 '1<1'
assert 0 '2<1'
assert 1 '0<=1'
assert 1 '1<=1'
assert 0 '2<=1'

assert 1 '1>0'
assert 0 '1>1'
assert 0 '1>2'
assert 1 '1>=0'
assert 1 '1>=1'
assert 0 '1>=2'

echo OK
